services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DATABASE: 'edition-limitee'
      POSTGRES_USER: 'edition-limitee'
      POSTGRES_PASSWORD: 'edition-limitee'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
